version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"  
    volumes:
      - .:/usr/local/app  
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001
    command: flask run
